"""
✨ `Circuito_KeyOutput` returns the primary key fields of table type `Circuito`.

It has the same format as `Circuito_Key`, but is only used as mutation return value.
"""
scalar Circuito_KeyOutput
"""
✨ `Destino_KeyOutput` returns the primary key fields of table type `Destino`.

It has the same format as `Destino_Key`, but is only used as mutation return value.
"""
scalar Destino_KeyOutput
"""
✨ `Hotel_KeyOutput` returns the primary key fields of table type `Hotel`.

It has the same format as `Hotel_Key`, but is only used as mutation return value.
"""
scalar Hotel_KeyOutput
"""
✨ `Itinerario_KeyOutput` returns the primary key fields of table type `Itinerario`.

It has the same format as `Itinerario_Key`, but is only used as mutation return value.
"""
scalar Itinerario_KeyOutput
"""
✨ `Paquete_KeyOutput` returns the primary key fields of table type `Paquete`.

It has the same format as `Paquete_Key`, but is only used as mutation return value.
"""
scalar Paquete_KeyOutput
"""
✨ `Promocion_KeyOutput` returns the primary key fields of table type `Promocion`.

It has the same format as `Promocion_Key`, but is only used as mutation return value.
"""
scalar Promocion_KeyOutput
"""
✨ `Reservacion_KeyOutput` returns the primary key fields of table type `Reservacion`.

It has the same format as `Reservacion_Key`, but is only used as mutation return value.
"""
scalar Reservacion_KeyOutput
"""
✨ `Tarifa_KeyOutput` returns the primary key fields of table type `Tarifa`.

It has the same format as `Tarifa_Key`, but is only used as mutation return value.
"""
scalar Tarifa_KeyOutput
"""
✨ `User_KeyOutput` returns the primary key fields of table type `User`.

It has the same format as `User_Key`, but is only used as mutation return value.
"""
scalar User_KeyOutput
"""
✨ Generated data input type for table 'Circuito'. It includes all necessary fields for creating or upserting rows into table.
"""
input Circuito_Data {
  """
  ✨ Generated from Field `Circuito`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Circuito`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`destinoId` of type `UUID`
  """
  destinoId: UUID
  """
  ✨ `_expr` server value variant of `destinoId` (✨ Generated from Field `Circuito`.`destinoId` of type `UUID`)
  """
  destinoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`destino` of type `Destino`
  """
  destino: Destino_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`activo` of type `Boolean!`
  """
  activo: Boolean
  """
  ✨ `_expr` server value variant of `activo` (✨ Generated from Field `Circuito`.`activo` of type `Boolean!`)
  """
  activo_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`ciudades` of type `String`
  """
  ciudades: String
  """
  ✨ `_expr` server value variant of `ciudades` (✨ Generated from Field `Circuito`.`ciudades` of type `String`)
  """
  ciudades_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`descripcion` of type `String`
  """
  descripcion: String
  """
  ✨ `_expr` server value variant of `descripcion` (✨ Generated from Field `Circuito`.`descripcion` of type `String`)
  """
  descripcion_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`destacado` of type `Boolean!`
  """
  destacado: Boolean
  """
  ✨ `_expr` server value variant of `destacado` (✨ Generated from Field `Circuito`.`destacado` of type `Boolean!`)
  """
  destacado_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`duracionDias` of type `Int!`
  """
  duracionDias: Int
  """
  ✨ `_expr` server value variant of `duracionDias` (✨ Generated from Field `Circuito`.`duracionDias` of type `Int!`)
  """
  duracionDias_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `duracionDias` (✨ Generated from Field `Circuito`.`duracionDias` of type `Int!`)
  """
  duracionDias_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`imagenUrl` of type `String`
  """
  imagenUrl: String
  """
  ✨ `_expr` server value variant of `imagenUrl` (✨ Generated from Field `Circuito`.`imagenUrl` of type `String`)
  """
  imagenUrl_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd` of type `Float!`
  """
  impuestosUsd: Float
  """
  ✨ `_expr` server value variant of `impuestosUsd` (✨ Generated from Field `Circuito`.`impuestosUsd` of type `Float!`)
  """
  impuestosUsd_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `impuestosUsd` (✨ Generated from Field `Circuito`.`impuestosUsd` of type `Float!`)
  """
  impuestosUsd_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`nombre` of type `String!`
  """
  nombre: String
  """
  ✨ `_expr` server value variant of `nombre` (✨ Generated from Field `Circuito`.`nombre` of type `String!`)
  """
  nombre_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`paises` of type `String`
  """
  paises: String
  """
  ✨ `_expr` server value variant of `paises` (✨ Generated from Field `Circuito`.`paises` of type `String`)
  """
  paises_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`precioUsd` of type `Float!`
  """
  precioUsd: Float
  """
  ✨ `_expr` server value variant of `precioUsd` (✨ Generated from Field `Circuito`.`precioUsd` of type `Float!`)
  """
  precioUsd_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `precioUsd` (✨ Generated from Field `Circuito`.`precioUsd` of type `Float!`)
  """
  precioUsd_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Circuito`.`tipoHabitacion` of type `String`
  """
  tipoHabitacion: String
  """
  ✨ `_expr` server value variant of `tipoHabitacion` (✨ Generated from Field `Circuito`.`tipoHabitacion` of type `String`)
  """
  tipoHabitacion_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Circuito'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Circuito_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Circuito_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Circuito_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Circuito_Filter!]
  """
  ✨ Generated from Field `Circuito`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Circuito`.`destinoId` of type `UUID`
  """
  destinoId: UUID_Filter
  """
  ✨ Generated from Field `Circuito`.`destino` of type `Destino`
  """
  destino: Destino_Filter
  """
  ✨ Generated from Field `Circuito`.`activo` of type `Boolean!`
  """
  activo: Boolean_Filter
  """
  ✨ Generated from Field `Circuito`.`ciudades` of type `String`
  """
  ciudades: String_Filter
  """
  ✨ Generated from Field `Circuito`.`descripcion` of type `String`
  """
  descripcion: String_Filter
  """
  ✨ Generated from Field `Circuito`.`destacado` of type `Boolean!`
  """
  destacado: Boolean_Filter
  """
  ✨ Generated from Field `Circuito`.`duracionDias` of type `Int!`
  """
  duracionDias: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`imagenUrl` of type `String`
  """
  imagenUrl: String_Filter
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd` of type `Float!`
  """
  impuestosUsd: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`nombre` of type `String!`
  """
  nombre: String_Filter
  """
  ✨ Generated from Field `Circuito`.`paises` of type `String`
  """
  paises: String_Filter
  """
  ✨ Generated from Field `Circuito`.`precioUsd` of type `Float!`
  """
  precioUsd: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`tipoHabitacion` of type `String`
  """
  tipoHabitacion: String_Filter
  """
  ✨ Generated from Field `Circuito`.`hotels_on_circuito` of type `[Hotel!]!`
  """
  hotels_on_circuito: Hotel_ListFilter
  """
  ✨ Generated from Field `Circuito`.`itinerarios_on_circuito` of type `[Itinerario!]!`
  """
  itinerarios_on_circuito: Itinerario_ListFilter
  """
  ✨ Generated from Field `Circuito`.`paquetes_on_circuito` of type `[Paquete!]!`
  """
  paquetes_on_circuito: Paquete_ListFilter
  """
  ✨ Generated from Field `Circuito`.`promocions_on_circuito` of type `[Promocion!]!`
  """
  promocions_on_circuito: Promocion_ListFilter
  """
  ✨ Generated from Field `Circuito`.`reservacions_on_circuito` of type `[Reservacion!]!`
  """
  reservacions_on_circuito: Reservacion_ListFilter
  """
  ✨ Generated from Field `Circuito`.`tarifas_on_circuito` of type `[Tarifa!]!`
  """
  tarifas_on_circuito: Tarifa_ListFilter
}
"""
✨ Generated first-row input type for table 'Circuito'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Circuito_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Circuito_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Circuito_Filter
}
"""
✨ Generated having input type for table 'Circuito'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Circuito_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Circuito_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Circuito_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Circuito_Having!]
  """
  ✨ Generated from Field `Circuito`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`activo_count` of type `Int!`
  """
  activo_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`ciudades_count` of type `Int!`
  """
  ciudades_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`descripcion_count` of type `Int!`
  """
  descripcion_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`destacado_count` of type `Int!`
  """
  destacado_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`destinoId_count` of type `Int!`
  """
  destinoId_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`duracionDias_count` of type `Int!`
  """
  duracionDias_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`imagenUrl_count` of type `Int!`
  """
  imagenUrl_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_count` of type `Int!`
  """
  impuestosUsd_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`nombre_count` of type `Int!`
  """
  nombre_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`paises_count` of type `Int!`
  """
  paises_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`precioUsd_count` of type `Int!`
  """
  precioUsd_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`tipoHabitacion_count` of type `Int!`
  """
  tipoHabitacion_count: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`duracionDias_sum` of type `Int`
  """
  duracionDias_sum: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_sum` of type `Float`
  """
  impuestosUsd_sum: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`precioUsd_sum` of type `Float`
  """
  precioUsd_sum: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`duracionDias_avg` of type `Float`
  """
  duracionDias_avg: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_avg` of type `Float`
  """
  impuestosUsd_avg: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`precioUsd_avg` of type `Float`
  """
  precioUsd_avg: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`duracionDias_min` of type `Int`
  """
  duracionDias_min: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_min` of type `Float`
  """
  impuestosUsd_min: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`precioUsd_min` of type `Float`
  """
  precioUsd_min: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`duracionDias_max` of type `Int`
  """
  duracionDias_max: Int_Filter
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_max` of type `Float`
  """
  impuestosUsd_max: Float_Filter
  """
  ✨ Generated from Field `Circuito`.`precioUsd_max` of type `Float`
  """
  precioUsd_max: Float_Filter
}
"""
✨ Generated key input type for table 'Circuito'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Circuito_Key {
  """
  ✨ Generated from Field `Circuito`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Circuito`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Circuito'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Circuito_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Circuito_Filter
}
"""
✨ Generated order input type for table 'Circuito'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Circuito_Order {
  """
  ✨ Generated from Field `Circuito`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`destinoId` of type `UUID`
  """
  destinoId: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`destino` of type `Destino`
  """
  destino: Destino_Order
  """
  ✨ Generated from Field `Circuito`.`activo` of type `Boolean!`
  """
  activo: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`ciudades` of type `String`
  """
  ciudades: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`descripcion` of type `String`
  """
  descripcion: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`destacado` of type `Boolean!`
  """
  destacado: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`duracionDias` of type `Int!`
  """
  duracionDias: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`imagenUrl` of type `String`
  """
  imagenUrl: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd` of type `Float!`
  """
  impuestosUsd: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`nombre` of type `String!`
  """
  nombre: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`paises` of type `String`
  """
  paises: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`precioUsd` of type `Float!`
  """
  precioUsd: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`tipoHabitacion` of type `String`
  """
  tipoHabitacion: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`activo_count` of type `Int!`
  """
  activo_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`ciudades_count` of type `Int!`
  """
  ciudades_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`descripcion_count` of type `Int!`
  """
  descripcion_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`destacado_count` of type `Int!`
  """
  destacado_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`destinoId_count` of type `Int!`
  """
  destinoId_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`duracionDias_count` of type `Int!`
  """
  duracionDias_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`imagenUrl_count` of type `Int!`
  """
  imagenUrl_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_count` of type `Int!`
  """
  impuestosUsd_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`nombre_count` of type `Int!`
  """
  nombre_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`paises_count` of type `Int!`
  """
  paises_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`precioUsd_count` of type `Int!`
  """
  precioUsd_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`tipoHabitacion_count` of type `Int!`
  """
  tipoHabitacion_count: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`duracionDias_sum` of type `Int`
  """
  duracionDias_sum: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_sum` of type `Float`
  """
  impuestosUsd_sum: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`precioUsd_sum` of type `Float`
  """
  precioUsd_sum: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`duracionDias_avg` of type `Float`
  """
  duracionDias_avg: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_avg` of type `Float`
  """
  impuestosUsd_avg: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`precioUsd_avg` of type `Float`
  """
  precioUsd_avg: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`duracionDias_min` of type `Int`
  """
  duracionDias_min: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_min` of type `Float`
  """
  impuestosUsd_min: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`precioUsd_min` of type `Float`
  """
  precioUsd_min: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`duracionDias_max` of type `Int`
  """
  duracionDias_max: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`impuestosUsd_max` of type `Float`
  """
  impuestosUsd_max: OrderDirection
  """
  ✨ Generated from Field `Circuito`.`precioUsd_max` of type `Float`
  """
  precioUsd_max: OrderDirection
}
"""
✨ Generated data input type for table 'Destino'. It includes all necessary fields for creating or upserting rows into table.
"""
input Destino_Data {
  """
  ✨ Generated from Field `Destino`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Destino`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Destino`.`activo` of type `Boolean!`
  """
  activo: Boolean
  """
  ✨ `_expr` server value variant of `activo` (✨ Generated from Field `Destino`.`activo` of type `Boolean!`)
  """
  activo_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Destino`.`descripcion` of type `String`
  """
  descripcion: String
  """
  ✨ `_expr` server value variant of `descripcion` (✨ Generated from Field `Destino`.`descripcion` of type `String`)
  """
  descripcion_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Destino`.`imagenUrl` of type `String`
  """
  imagenUrl: String
  """
  ✨ `_expr` server value variant of `imagenUrl` (✨ Generated from Field `Destino`.`imagenUrl` of type `String`)
  """
  imagenUrl_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Destino`.`nombre` of type `String!`
  """
  nombre: String
  """
  ✨ `_expr` server value variant of `nombre` (✨ Generated from Field `Destino`.`nombre` of type `String!`)
  """
  nombre_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Destino`.`orden` of type `Int`
  """
  orden: Int
  """
  ✨ `_expr` server value variant of `orden` (✨ Generated from Field `Destino`.`orden` of type `Int`)
  """
  orden_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `orden` (✨ Generated from Field `Destino`.`orden` of type `Int`)
  """
  orden_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Destino`.`slug` of type `String!`
  """
  slug: String
  """
  ✨ `_expr` server value variant of `slug` (✨ Generated from Field `Destino`.`slug` of type `String!`)
  """
  slug_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Destino'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Destino_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Destino_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Destino_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Destino_Filter!]
  """
  ✨ Generated from Field `Destino`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Destino`.`activo` of type `Boolean!`
  """
  activo: Boolean_Filter
  """
  ✨ Generated from Field `Destino`.`descripcion` of type `String`
  """
  descripcion: String_Filter
  """
  ✨ Generated from Field `Destino`.`imagenUrl` of type `String`
  """
  imagenUrl: String_Filter
  """
  ✨ Generated from Field `Destino`.`nombre` of type `String!`
  """
  nombre: String_Filter
  """
  ✨ Generated from Field `Destino`.`orden` of type `Int`
  """
  orden: Int_Filter
  """
  ✨ Generated from Field `Destino`.`slug` of type `String!`
  """
  slug: String_Filter
  """
  ✨ Generated from Field `Destino`.`circuitos_on_destino` of type `[Circuito!]!`
  """
  circuitos_on_destino: Circuito_ListFilter
  """
  ✨ Generated from Field `Destino`.`paquetes_on_destino` of type `[Paquete!]!`
  """
  paquetes_on_destino: Paquete_ListFilter
}
"""
✨ Generated first-row input type for table 'Destino'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Destino_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Destino_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Destino_Filter
}
"""
✨ Generated having input type for table 'Destino'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Destino_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Destino_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Destino_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Destino_Having!]
  """
  ✨ Generated from Field `Destino`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Destino`.`activo_count` of type `Int!`
  """
  activo_count: Int_Filter
  """
  ✨ Generated from Field `Destino`.`descripcion_count` of type `Int!`
  """
  descripcion_count: Int_Filter
  """
  ✨ Generated from Field `Destino`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Destino`.`imagenUrl_count` of type `Int!`
  """
  imagenUrl_count: Int_Filter
  """
  ✨ Generated from Field `Destino`.`nombre_count` of type `Int!`
  """
  nombre_count: Int_Filter
  """
  ✨ Generated from Field `Destino`.`orden_count` of type `Int!`
  """
  orden_count: Int_Filter
  """
  ✨ Generated from Field `Destino`.`slug_count` of type `Int!`
  """
  slug_count: Int_Filter
  """
  ✨ Generated from Field `Destino`.`orden_sum` of type `Int`
  """
  orden_sum: Int_Filter
  """
  ✨ Generated from Field `Destino`.`orden_avg` of type `Float`
  """
  orden_avg: Float_Filter
  """
  ✨ Generated from Field `Destino`.`orden_min` of type `Int`
  """
  orden_min: Int_Filter
  """
  ✨ Generated from Field `Destino`.`orden_max` of type `Int`
  """
  orden_max: Int_Filter
}
"""
✨ Generated key input type for table 'Destino'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Destino_Key {
  """
  ✨ Generated from Field `Destino`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Destino`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Destino'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Destino_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Destino_Filter
}
"""
✨ Generated order input type for table 'Destino'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Destino_Order {
  """
  ✨ Generated from Field `Destino`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Destino`.`activo` of type `Boolean!`
  """
  activo: OrderDirection
  """
  ✨ Generated from Field `Destino`.`descripcion` of type `String`
  """
  descripcion: OrderDirection
  """
  ✨ Generated from Field `Destino`.`imagenUrl` of type `String`
  """
  imagenUrl: OrderDirection
  """
  ✨ Generated from Field `Destino`.`nombre` of type `String!`
  """
  nombre: OrderDirection
  """
  ✨ Generated from Field `Destino`.`orden` of type `Int`
  """
  orden: OrderDirection
  """
  ✨ Generated from Field `Destino`.`slug` of type `String!`
  """
  slug: OrderDirection
  """
  ✨ Generated from Field `Destino`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Destino`.`activo_count` of type `Int!`
  """
  activo_count: OrderDirection
  """
  ✨ Generated from Field `Destino`.`descripcion_count` of type `Int!`
  """
  descripcion_count: OrderDirection
  """
  ✨ Generated from Field `Destino`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Destino`.`imagenUrl_count` of type `Int!`
  """
  imagenUrl_count: OrderDirection
  """
  ✨ Generated from Field `Destino`.`nombre_count` of type `Int!`
  """
  nombre_count: OrderDirection
  """
  ✨ Generated from Field `Destino`.`orden_count` of type `Int!`
  """
  orden_count: OrderDirection
  """
  ✨ Generated from Field `Destino`.`slug_count` of type `Int!`
  """
  slug_count: OrderDirection
  """
  ✨ Generated from Field `Destino`.`orden_sum` of type `Int`
  """
  orden_sum: OrderDirection
  """
  ✨ Generated from Field `Destino`.`orden_avg` of type `Float`
  """
  orden_avg: OrderDirection
  """
  ✨ Generated from Field `Destino`.`orden_min` of type `Int`
  """
  orden_min: OrderDirection
  """
  ✨ Generated from Field `Destino`.`orden_max` of type `Int`
  """
  orden_max: OrderDirection
}
"""
✨ Generated data input type for table 'Hotel'. It includes all necessary fields for creating or upserting rows into table.
"""
input Hotel_Data {
  """
  ✨ Generated from Field `Hotel`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Hotel`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID
  """
  ✨ `_expr` server value variant of `circuitoId` (✨ Generated from Field `Hotel`.`circuitoId` of type `UUID`)
  """
  circuitoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`ciudad` of type `String`
  """
  ciudad: String
  """
  ✨ `_expr` server value variant of `ciudad` (✨ Generated from Field `Hotel`.`ciudad` of type `String`)
  """
  ciudad_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`nombre` of type `String!`
  """
  nombre: String
  """
  ✨ `_expr` server value variant of `nombre` (✨ Generated from Field `Hotel`.`nombre` of type `String!`)
  """
  nombre_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`pais` of type `String`
  """
  pais: String
  """
  ✨ `_expr` server value variant of `pais` (✨ Generated from Field `Hotel`.`pais` of type `String`)
  """
  pais_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`tipo` of type `String`
  """
  tipo: String
  """
  ✨ `_expr` server value variant of `tipo` (✨ Generated from Field `Hotel`.`tipo` of type `String`)
  """
  tipo_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Hotel'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Hotel_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Hotel_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Hotel_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Hotel_Filter!]
  """
  ✨ Generated from Field `Hotel`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Hotel`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID_Filter
  """
  ✨ Generated from Field `Hotel`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Filter
  """
  ✨ Generated from Field `Hotel`.`ciudad` of type `String`
  """
  ciudad: String_Filter
  """
  ✨ Generated from Field `Hotel`.`nombre` of type `String!`
  """
  nombre: String_Filter
  """
  ✨ Generated from Field `Hotel`.`pais` of type `String`
  """
  pais: String_Filter
  """
  ✨ Generated from Field `Hotel`.`tipo` of type `String`
  """
  tipo: String_Filter
}
"""
✨ Generated first-row input type for table 'Hotel'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Hotel_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Hotel_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Hotel_Filter
}
"""
✨ Generated having input type for table 'Hotel'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Hotel_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Hotel_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Hotel_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Hotel_Having!]
  """
  ✨ Generated from Field `Hotel`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`ciudad_count` of type `Int!`
  """
  ciudad_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`nombre_count` of type `Int!`
  """
  nombre_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`pais_count` of type `Int!`
  """
  pais_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`tipo_count` of type `Int!`
  """
  tipo_count: Int_Filter
}
"""
✨ Generated key input type for table 'Hotel'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Hotel_Key {
  """
  ✨ Generated from Field `Hotel`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Hotel`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Hotel'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Hotel_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Hotel_Filter
}
"""
✨ Generated order input type for table 'Hotel'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Hotel_Order {
  """
  ✨ Generated from Field `Hotel`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`circuitoId` of type `UUID`
  """
  circuitoId: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Order
  """
  ✨ Generated from Field `Hotel`.`ciudad` of type `String`
  """
  ciudad: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`nombre` of type `String!`
  """
  nombre: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`pais` of type `String`
  """
  pais: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`tipo` of type `String`
  """
  tipo: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`ciudad_count` of type `Int!`
  """
  ciudad_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`nombre_count` of type `Int!`
  """
  nombre_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`pais_count` of type `Int!`
  """
  pais_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`tipo_count` of type `Int!`
  """
  tipo_count: OrderDirection
}
"""
✨ Generated data input type for table 'Itinerario'. It includes all necessary fields for creating or upserting rows into table.
"""
input Itinerario_Data {
  """
  ✨ Generated from Field `Itinerario`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Itinerario`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Itinerario`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID
  """
  ✨ `_expr` server value variant of `circuitoId` (✨ Generated from Field `Itinerario`.`circuitoId` of type `UUID`)
  """
  circuitoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Itinerario`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Itinerario`.`descripcion` of type `String!`
  """
  descripcion: String
  """
  ✨ `_expr` server value variant of `descripcion` (✨ Generated from Field `Itinerario`.`descripcion` of type `String!`)
  """
  descripcion_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Itinerario`.`dia` of type `Int!`
  """
  dia: Int
  """
  ✨ `_expr` server value variant of `dia` (✨ Generated from Field `Itinerario`.`dia` of type `Int!`)
  """
  dia_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `dia` (✨ Generated from Field `Itinerario`.`dia` of type `Int!`)
  """
  dia_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Itinerario`.`titulo` of type `String!`
  """
  titulo: String
  """
  ✨ `_expr` server value variant of `titulo` (✨ Generated from Field `Itinerario`.`titulo` of type `String!`)
  """
  titulo_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Itinerario'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Itinerario_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Itinerario_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Itinerario_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Itinerario_Filter!]
  """
  ✨ Generated from Field `Itinerario`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Itinerario`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID_Filter
  """
  ✨ Generated from Field `Itinerario`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Filter
  """
  ✨ Generated from Field `Itinerario`.`descripcion` of type `String!`
  """
  descripcion: String_Filter
  """
  ✨ Generated from Field `Itinerario`.`dia` of type `Int!`
  """
  dia: Int_Filter
  """
  ✨ Generated from Field `Itinerario`.`titulo` of type `String!`
  """
  titulo: String_Filter
}
"""
✨ Generated first-row input type for table 'Itinerario'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Itinerario_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Itinerario_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Itinerario_Filter
}
"""
✨ Generated having input type for table 'Itinerario'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Itinerario_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Itinerario_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Itinerario_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Itinerario_Having!]
  """
  ✨ Generated from Field `Itinerario`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Itinerario`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: Int_Filter
  """
  ✨ Generated from Field `Itinerario`.`descripcion_count` of type `Int!`
  """
  descripcion_count: Int_Filter
  """
  ✨ Generated from Field `Itinerario`.`dia_count` of type `Int!`
  """
  dia_count: Int_Filter
  """
  ✨ Generated from Field `Itinerario`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Itinerario`.`titulo_count` of type `Int!`
  """
  titulo_count: Int_Filter
  """
  ✨ Generated from Field `Itinerario`.`dia_sum` of type `Int`
  """
  dia_sum: Int_Filter
  """
  ✨ Generated from Field `Itinerario`.`dia_avg` of type `Float`
  """
  dia_avg: Float_Filter
  """
  ✨ Generated from Field `Itinerario`.`dia_min` of type `Int`
  """
  dia_min: Int_Filter
  """
  ✨ Generated from Field `Itinerario`.`dia_max` of type `Int`
  """
  dia_max: Int_Filter
}
"""
✨ Generated key input type for table 'Itinerario'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Itinerario_Key {
  """
  ✨ Generated from Field `Itinerario`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Itinerario`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Itinerario'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Itinerario_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Itinerario_Filter
}
"""
✨ Generated order input type for table 'Itinerario'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Itinerario_Order {
  """
  ✨ Generated from Field `Itinerario`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`circuitoId` of type `UUID`
  """
  circuitoId: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Order
  """
  ✨ Generated from Field `Itinerario`.`descripcion` of type `String!`
  """
  descripcion: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`dia` of type `Int!`
  """
  dia: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`titulo` of type `String!`
  """
  titulo: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`descripcion_count` of type `Int!`
  """
  descripcion_count: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`dia_count` of type `Int!`
  """
  dia_count: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`titulo_count` of type `Int!`
  """
  titulo_count: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`dia_sum` of type `Int`
  """
  dia_sum: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`dia_avg` of type `Float`
  """
  dia_avg: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`dia_min` of type `Int`
  """
  dia_min: OrderDirection
  """
  ✨ Generated from Field `Itinerario`.`dia_max` of type `Int`
  """
  dia_max: OrderDirection
}
"""
✨ Generated data input type for table 'Paquete'. It includes all necessary fields for creating or upserting rows into table.
"""
input Paquete_Data {
  """
  ✨ Generated from Field `Paquete`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Paquete`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID
  """
  ✨ `_expr` server value variant of `circuitoId` (✨ Generated from Field `Paquete`.`circuitoId` of type `UUID`)
  """
  circuitoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`destinoId` of type `UUID`
  """
  destinoId: UUID
  """
  ✨ `_expr` server value variant of `destinoId` (✨ Generated from Field `Paquete`.`destinoId` of type `UUID`)
  """
  destinoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`destino` of type `Destino`
  """
  destino: Destino_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`activo` of type `Boolean!`
  """
  activo: Boolean
  """
  ✨ `_expr` server value variant of `activo` (✨ Generated from Field `Paquete`.`activo` of type `Boolean!`)
  """
  activo_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`ciudades` of type `String`
  """
  ciudades: String
  """
  ✨ `_expr` server value variant of `ciudades` (✨ Generated from Field `Paquete`.`ciudades` of type `String`)
  """
  ciudades_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`codigo` of type `String!`
  """
  codigo: String
  """
  ✨ `_expr` server value variant of `codigo` (✨ Generated from Field `Paquete`.`codigo` of type `String!`)
  """
  codigo_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`duracionDias` of type `Int!`
  """
  duracionDias: Int
  """
  ✨ `_expr` server value variant of `duracionDias` (✨ Generated from Field `Paquete`.`duracionDias` of type `Int!`)
  """
  duracionDias_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `duracionDias` (✨ Generated from Field `Paquete`.`duracionDias` of type `Int!`)
  """
  duracionDias_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd` of type `Float!`
  """
  impuestosUsd: Float
  """
  ✨ `_expr` server value variant of `impuestosUsd` (✨ Generated from Field `Paquete`.`impuestosUsd` of type `Float!`)
  """
  impuestosUsd_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `impuestosUsd` (✨ Generated from Field `Paquete`.`impuestosUsd` of type `Float!`)
  """
  impuestosUsd_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`nombre` of type `String!`
  """
  nombre: String
  """
  ✨ `_expr` server value variant of `nombre` (✨ Generated from Field `Paquete`.`nombre` of type `String!`)
  """
  nombre_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Paquete`.`precioUsd` of type `Float!`
  """
  precioUsd: Float
  """
  ✨ `_expr` server value variant of `precioUsd` (✨ Generated from Field `Paquete`.`precioUsd` of type `Float!`)
  """
  precioUsd_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `precioUsd` (✨ Generated from Field `Paquete`.`precioUsd` of type `Float!`)
  """
  precioUsd_update: [Float_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Paquete'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Paquete_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Paquete_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Paquete_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Paquete_Filter!]
  """
  ✨ Generated from Field `Paquete`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Paquete`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID_Filter
  """
  ✨ Generated from Field `Paquete`.`destinoId` of type `UUID`
  """
  destinoId: UUID_Filter
  """
  ✨ Generated from Field `Paquete`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Filter
  """
  ✨ Generated from Field `Paquete`.`destino` of type `Destino`
  """
  destino: Destino_Filter
  """
  ✨ Generated from Field `Paquete`.`activo` of type `Boolean!`
  """
  activo: Boolean_Filter
  """
  ✨ Generated from Field `Paquete`.`ciudades` of type `String`
  """
  ciudades: String_Filter
  """
  ✨ Generated from Field `Paquete`.`codigo` of type `String!`
  """
  codigo: String_Filter
  """
  ✨ Generated from Field `Paquete`.`duracionDias` of type `Int!`
  """
  duracionDias: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd` of type `Float!`
  """
  impuestosUsd: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`nombre` of type `String!`
  """
  nombre: String_Filter
  """
  ✨ Generated from Field `Paquete`.`precioUsd` of type `Float!`
  """
  precioUsd: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`reservacions_on_paquete` of type `[Reservacion!]!`
  """
  reservacions_on_paquete: Reservacion_ListFilter
}
"""
✨ Generated first-row input type for table 'Paquete'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Paquete_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Paquete_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Paquete_Filter
}
"""
✨ Generated having input type for table 'Paquete'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Paquete_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Paquete_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Paquete_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Paquete_Having!]
  """
  ✨ Generated from Field `Paquete`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`activo_count` of type `Int!`
  """
  activo_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`ciudades_count` of type `Int!`
  """
  ciudades_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`codigo_count` of type `Int!`
  """
  codigo_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`destinoId_count` of type `Int!`
  """
  destinoId_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`duracionDias_count` of type `Int!`
  """
  duracionDias_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_count` of type `Int!`
  """
  impuestosUsd_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`nombre_count` of type `Int!`
  """
  nombre_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`precioUsd_count` of type `Int!`
  """
  precioUsd_count: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`duracionDias_sum` of type `Int`
  """
  duracionDias_sum: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_sum` of type `Float`
  """
  impuestosUsd_sum: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`precioUsd_sum` of type `Float`
  """
  precioUsd_sum: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`duracionDias_avg` of type `Float`
  """
  duracionDias_avg: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_avg` of type `Float`
  """
  impuestosUsd_avg: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`precioUsd_avg` of type `Float`
  """
  precioUsd_avg: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`duracionDias_min` of type `Int`
  """
  duracionDias_min: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_min` of type `Float`
  """
  impuestosUsd_min: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`precioUsd_min` of type `Float`
  """
  precioUsd_min: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`duracionDias_max` of type `Int`
  """
  duracionDias_max: Int_Filter
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_max` of type `Float`
  """
  impuestosUsd_max: Float_Filter
  """
  ✨ Generated from Field `Paquete`.`precioUsd_max` of type `Float`
  """
  precioUsd_max: Float_Filter
}
"""
✨ Generated key input type for table 'Paquete'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Paquete_Key {
  """
  ✨ Generated from Field `Paquete`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Paquete`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Paquete'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Paquete_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Paquete_Filter
}
"""
✨ Generated order input type for table 'Paquete'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Paquete_Order {
  """
  ✨ Generated from Field `Paquete`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`circuitoId` of type `UUID`
  """
  circuitoId: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`destinoId` of type `UUID`
  """
  destinoId: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Order
  """
  ✨ Generated from Field `Paquete`.`destino` of type `Destino`
  """
  destino: Destino_Order
  """
  ✨ Generated from Field `Paquete`.`activo` of type `Boolean!`
  """
  activo: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`ciudades` of type `String`
  """
  ciudades: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`codigo` of type `String!`
  """
  codigo: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`duracionDias` of type `Int!`
  """
  duracionDias: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd` of type `Float!`
  """
  impuestosUsd: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`nombre` of type `String!`
  """
  nombre: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`precioUsd` of type `Float!`
  """
  precioUsd: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`activo_count` of type `Int!`
  """
  activo_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`ciudades_count` of type `Int!`
  """
  ciudades_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`codigo_count` of type `Int!`
  """
  codigo_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`destinoId_count` of type `Int!`
  """
  destinoId_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`duracionDias_count` of type `Int!`
  """
  duracionDias_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_count` of type `Int!`
  """
  impuestosUsd_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`nombre_count` of type `Int!`
  """
  nombre_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`precioUsd_count` of type `Int!`
  """
  precioUsd_count: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`duracionDias_sum` of type `Int`
  """
  duracionDias_sum: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_sum` of type `Float`
  """
  impuestosUsd_sum: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`precioUsd_sum` of type `Float`
  """
  precioUsd_sum: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`duracionDias_avg` of type `Float`
  """
  duracionDias_avg: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_avg` of type `Float`
  """
  impuestosUsd_avg: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`precioUsd_avg` of type `Float`
  """
  precioUsd_avg: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`duracionDias_min` of type `Int`
  """
  duracionDias_min: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_min` of type `Float`
  """
  impuestosUsd_min: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`precioUsd_min` of type `Float`
  """
  precioUsd_min: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`duracionDias_max` of type `Int`
  """
  duracionDias_max: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`impuestosUsd_max` of type `Float`
  """
  impuestosUsd_max: OrderDirection
  """
  ✨ Generated from Field `Paquete`.`precioUsd_max` of type `Float`
  """
  precioUsd_max: OrderDirection
}
"""
✨ Generated data input type for table 'Promocion'. It includes all necessary fields for creating or upserting rows into table.
"""
input Promocion_Data {
  """
  ✨ Generated from Field `Promocion`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Promocion`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Promocion`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID
  """
  ✨ `_expr` server value variant of `circuitoId` (✨ Generated from Field `Promocion`.`circuitoId` of type `UUID`)
  """
  circuitoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Promocion`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Promocion`.`activo` of type `Boolean!`
  """
  activo: Boolean
  """
  ✨ `_expr` server value variant of `activo` (✨ Generated from Field `Promocion`.`activo` of type `Boolean!`)
  """
  activo_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Promocion`.`fechaFin` of type `Date`
  """
  fechaFin: Date
  """
  ✨ `_date` server value variant of `fechaFin` (✨ Generated from Field `Promocion`.`fechaFin` of type `Date`)
  """
  fechaFin_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fechaFin` (✨ Generated from Field `Promocion`.`fechaFin` of type `Date`)
  """
  fechaFin_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fechaFin` (✨ Generated from Field `Promocion`.`fechaFin` of type `Date`)
  """
  fechaFin_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Promocion`.`fechaInicio` of type `Date`
  """
  fechaInicio: Date
  """
  ✨ `_date` server value variant of `fechaInicio` (✨ Generated from Field `Promocion`.`fechaInicio` of type `Date`)
  """
  fechaInicio_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fechaInicio` (✨ Generated from Field `Promocion`.`fechaInicio` of type `Date`)
  """
  fechaInicio_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fechaInicio` (✨ Generated from Field `Promocion`.`fechaInicio` of type `Date`)
  """
  fechaInicio_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Promocion`.`imagenUrl` of type `String!`
  """
  imagenUrl: String
  """
  ✨ `_expr` server value variant of `imagenUrl` (✨ Generated from Field `Promocion`.`imagenUrl` of type `String!`)
  """
  imagenUrl_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Promocion`.`titulo` of type `String`
  """
  titulo: String
  """
  ✨ `_expr` server value variant of `titulo` (✨ Generated from Field `Promocion`.`titulo` of type `String`)
  """
  titulo_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Promocion'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Promocion_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Promocion_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Promocion_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Promocion_Filter!]
  """
  ✨ Generated from Field `Promocion`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Promocion`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID_Filter
  """
  ✨ Generated from Field `Promocion`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Filter
  """
  ✨ Generated from Field `Promocion`.`activo` of type `Boolean!`
  """
  activo: Boolean_Filter
  """
  ✨ Generated from Field `Promocion`.`fechaFin` of type `Date`
  """
  fechaFin: Date_Filter
  """
  ✨ Generated from Field `Promocion`.`fechaInicio` of type `Date`
  """
  fechaInicio: Date_Filter
  """
  ✨ Generated from Field `Promocion`.`imagenUrl` of type `String!`
  """
  imagenUrl: String_Filter
  """
  ✨ Generated from Field `Promocion`.`titulo` of type `String`
  """
  titulo: String_Filter
}
"""
✨ Generated first-row input type for table 'Promocion'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Promocion_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Promocion_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Promocion_Filter
}
"""
✨ Generated having input type for table 'Promocion'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Promocion_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Promocion_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Promocion_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Promocion_Having!]
  """
  ✨ Generated from Field `Promocion`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Promocion`.`activo_count` of type `Int!`
  """
  activo_count: Int_Filter
  """
  ✨ Generated from Field `Promocion`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: Int_Filter
  """
  ✨ Generated from Field `Promocion`.`fechaFin_count` of type `Int!`
  """
  fechaFin_count: Int_Filter
  """
  ✨ Generated from Field `Promocion`.`fechaInicio_count` of type `Int!`
  """
  fechaInicio_count: Int_Filter
  """
  ✨ Generated from Field `Promocion`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Promocion`.`imagenUrl_count` of type `Int!`
  """
  imagenUrl_count: Int_Filter
  """
  ✨ Generated from Field `Promocion`.`titulo_count` of type `Int!`
  """
  titulo_count: Int_Filter
  """
  ✨ Generated from Field `Promocion`.`fechaFin_min` of type `Date`
  """
  fechaFin_min: Date_Filter
  """
  ✨ Generated from Field `Promocion`.`fechaInicio_min` of type `Date`
  """
  fechaInicio_min: Date_Filter
  """
  ✨ Generated from Field `Promocion`.`fechaFin_max` of type `Date`
  """
  fechaFin_max: Date_Filter
  """
  ✨ Generated from Field `Promocion`.`fechaInicio_max` of type `Date`
  """
  fechaInicio_max: Date_Filter
}
"""
✨ Generated key input type for table 'Promocion'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Promocion_Key {
  """
  ✨ Generated from Field `Promocion`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Promocion`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Promocion'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Promocion_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Promocion_Filter
}
"""
✨ Generated order input type for table 'Promocion'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Promocion_Order {
  """
  ✨ Generated from Field `Promocion`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`circuitoId` of type `UUID`
  """
  circuitoId: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Order
  """
  ✨ Generated from Field `Promocion`.`activo` of type `Boolean!`
  """
  activo: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`fechaFin` of type `Date`
  """
  fechaFin: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`fechaInicio` of type `Date`
  """
  fechaInicio: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`imagenUrl` of type `String!`
  """
  imagenUrl: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`titulo` of type `String`
  """
  titulo: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`activo_count` of type `Int!`
  """
  activo_count: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`fechaFin_count` of type `Int!`
  """
  fechaFin_count: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`fechaInicio_count` of type `Int!`
  """
  fechaInicio_count: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`imagenUrl_count` of type `Int!`
  """
  imagenUrl_count: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`titulo_count` of type `Int!`
  """
  titulo_count: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`fechaFin_min` of type `Date`
  """
  fechaFin_min: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`fechaInicio_min` of type `Date`
  """
  fechaInicio_min: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`fechaFin_max` of type `Date`
  """
  fechaFin_max: OrderDirection
  """
  ✨ Generated from Field `Promocion`.`fechaInicio_max` of type `Date`
  """
  fechaInicio_max: OrderDirection
}
"""
✨ Generated data input type for table 'Reservacion'. It includes all necessary fields for creating or upserting rows into table.
"""
input Reservacion_Data {
  """
  ✨ Generated from Field `Reservacion`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Reservacion`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID
  """
  ✨ `_expr` server value variant of `circuitoId` (✨ Generated from Field `Reservacion`.`circuitoId` of type `UUID`)
  """
  circuitoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`paqueteId` of type `UUID`
  """
  paqueteId: UUID
  """
  ✨ `_expr` server value variant of `paqueteId` (✨ Generated from Field `Reservacion`.`paqueteId` of type `UUID`)
  """
  paqueteId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`usuarioId` of type `String`
  """
  usuarioId: String
  """
  ✨ `_expr` server value variant of `usuarioId` (✨ Generated from Field `Reservacion`.`usuarioId` of type `String`)
  """
  usuarioId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`paquete` of type `Paquete`
  """
  paquete: Paquete_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`usuario` of type `User`
  """
  usuario: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`estatus` of type `String!`
  """
  estatus: String
  """
  ✨ `_expr` server value variant of `estatus` (✨ Generated from Field `Reservacion`.`estatus` of type `String!`)
  """
  estatus_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`fechaViaje` of type `Date!`
  """
  fechaViaje: Date
  """
  ✨ `_date` server value variant of `fechaViaje` (✨ Generated from Field `Reservacion`.`fechaViaje` of type `Date!`)
  """
  fechaViaje_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fechaViaje` (✨ Generated from Field `Reservacion`.`fechaViaje` of type `Date!`)
  """
  fechaViaje_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fechaViaje` (✨ Generated from Field `Reservacion`.`fechaViaje` of type `Date!`)
  """
  fechaViaje_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`notas` of type `String`
  """
  notas: String
  """
  ✨ `_expr` server value variant of `notas` (✨ Generated from Field `Reservacion`.`notas` of type `String`)
  """
  notas_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`numPersonas` of type `Int!`
  """
  numPersonas: Int
  """
  ✨ `_expr` server value variant of `numPersonas` (✨ Generated from Field `Reservacion`.`numPersonas` of type `Int!`)
  """
  numPersonas_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `numPersonas` (✨ Generated from Field `Reservacion`.`numPersonas` of type `Int!`)
  """
  numPersonas_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd` of type `Float!`
  """
  precioTotalUsd: Float
  """
  ✨ `_expr` server value variant of `precioTotalUsd` (✨ Generated from Field `Reservacion`.`precioTotalUsd` of type `Float!`)
  """
  precioTotalUsd_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `precioTotalUsd` (✨ Generated from Field `Reservacion`.`precioTotalUsd` of type `Float!`)
  """
  precioTotalUsd_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Reservacion`.`tipoHabitacion` of type `String`
  """
  tipoHabitacion: String
  """
  ✨ `_expr` server value variant of `tipoHabitacion` (✨ Generated from Field `Reservacion`.`tipoHabitacion` of type `String`)
  """
  tipoHabitacion_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Reservacion'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Reservacion_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Reservacion_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Reservacion_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Reservacion_Filter!]
  """
  ✨ Generated from Field `Reservacion`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Reservacion`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID_Filter
  """
  ✨ Generated from Field `Reservacion`.`paqueteId` of type `UUID`
  """
  paqueteId: UUID_Filter
  """
  ✨ Generated from Field `Reservacion`.`usuarioId` of type `String`
  """
  usuarioId: String_Filter
  """
  ✨ Generated from Field `Reservacion`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Filter
  """
  ✨ Generated from Field `Reservacion`.`paquete` of type `Paquete`
  """
  paquete: Paquete_Filter
  """
  ✨ Generated from Field `Reservacion`.`usuario` of type `User`
  """
  usuario: User_Filter
  """
  ✨ Generated from Field `Reservacion`.`estatus` of type `String!`
  """
  estatus: String_Filter
  """
  ✨ Generated from Field `Reservacion`.`fechaViaje` of type `Date!`
  """
  fechaViaje: Date_Filter
  """
  ✨ Generated from Field `Reservacion`.`notas` of type `String`
  """
  notas: String_Filter
  """
  ✨ Generated from Field `Reservacion`.`numPersonas` of type `Int!`
  """
  numPersonas: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd` of type `Float!`
  """
  precioTotalUsd: Float_Filter
  """
  ✨ Generated from Field `Reservacion`.`tipoHabitacion` of type `String`
  """
  tipoHabitacion: String_Filter
}
"""
✨ Generated first-row input type for table 'Reservacion'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Reservacion_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Reservacion_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Reservacion_Filter
}
"""
✨ Generated having input type for table 'Reservacion'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Reservacion_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Reservacion_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Reservacion_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Reservacion_Having!]
  """
  ✨ Generated from Field `Reservacion`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`estatus_count` of type `Int!`
  """
  estatus_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`fechaViaje_count` of type `Int!`
  """
  fechaViaje_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`notas_count` of type `Int!`
  """
  notas_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_count` of type `Int!`
  """
  numPersonas_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`paqueteId_count` of type `Int!`
  """
  paqueteId_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_count` of type `Int!`
  """
  precioTotalUsd_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`tipoHabitacion_count` of type `Int!`
  """
  tipoHabitacion_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`usuarioId_count` of type `Int!`
  """
  usuarioId_count: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_sum` of type `Int`
  """
  numPersonas_sum: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_sum` of type `Float`
  """
  precioTotalUsd_sum: Float_Filter
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_avg` of type `Float`
  """
  numPersonas_avg: Float_Filter
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_avg` of type `Float`
  """
  precioTotalUsd_avg: Float_Filter
  """
  ✨ Generated from Field `Reservacion`.`fechaViaje_min` of type `Date`
  """
  fechaViaje_min: Date_Filter
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_min` of type `Int`
  """
  numPersonas_min: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_min` of type `Float`
  """
  precioTotalUsd_min: Float_Filter
  """
  ✨ Generated from Field `Reservacion`.`fechaViaje_max` of type `Date`
  """
  fechaViaje_max: Date_Filter
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_max` of type `Int`
  """
  numPersonas_max: Int_Filter
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_max` of type `Float`
  """
  precioTotalUsd_max: Float_Filter
}
"""
✨ Generated key input type for table 'Reservacion'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Reservacion_Key {
  """
  ✨ Generated from Field `Reservacion`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Reservacion`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Reservacion'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Reservacion_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Reservacion_Filter
}
"""
✨ Generated order input type for table 'Reservacion'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Reservacion_Order {
  """
  ✨ Generated from Field `Reservacion`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`circuitoId` of type `UUID`
  """
  circuitoId: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`paqueteId` of type `UUID`
  """
  paqueteId: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`usuarioId` of type `String`
  """
  usuarioId: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Order
  """
  ✨ Generated from Field `Reservacion`.`paquete` of type `Paquete`
  """
  paquete: Paquete_Order
  """
  ✨ Generated from Field `Reservacion`.`usuario` of type `User`
  """
  usuario: User_Order
  """
  ✨ Generated from Field `Reservacion`.`estatus` of type `String!`
  """
  estatus: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`fechaViaje` of type `Date!`
  """
  fechaViaje: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`notas` of type `String`
  """
  notas: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`numPersonas` of type `Int!`
  """
  numPersonas: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd` of type `Float!`
  """
  precioTotalUsd: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`tipoHabitacion` of type `String`
  """
  tipoHabitacion: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`estatus_count` of type `Int!`
  """
  estatus_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`fechaViaje_count` of type `Int!`
  """
  fechaViaje_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`notas_count` of type `Int!`
  """
  notas_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_count` of type `Int!`
  """
  numPersonas_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`paqueteId_count` of type `Int!`
  """
  paqueteId_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_count` of type `Int!`
  """
  precioTotalUsd_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`tipoHabitacion_count` of type `Int!`
  """
  tipoHabitacion_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`usuarioId_count` of type `Int!`
  """
  usuarioId_count: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_sum` of type `Int`
  """
  numPersonas_sum: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_sum` of type `Float`
  """
  precioTotalUsd_sum: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_avg` of type `Float`
  """
  numPersonas_avg: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_avg` of type `Float`
  """
  precioTotalUsd_avg: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`fechaViaje_min` of type `Date`
  """
  fechaViaje_min: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_min` of type `Int`
  """
  numPersonas_min: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_min` of type `Float`
  """
  precioTotalUsd_min: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`fechaViaje_max` of type `Date`
  """
  fechaViaje_max: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`numPersonas_max` of type `Int`
  """
  numPersonas_max: OrderDirection
  """
  ✨ Generated from Field `Reservacion`.`precioTotalUsd_max` of type `Float`
  """
  precioTotalUsd_max: OrderDirection
}
"""
✨ Generated data input type for table 'Tarifa'. It includes all necessary fields for creating or upserting rows into table.
"""
input Tarifa_Data {
  """
  ✨ Generated from Field `Tarifa`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Tarifa`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tarifa`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID
  """
  ✨ `_expr` server value variant of `circuitoId` (✨ Generated from Field `Tarifa`.`circuitoId` of type `UUID`)
  """
  circuitoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tarifa`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tarifa`.`anio` of type `Int`
  """
  anio: Int
  """
  ✨ `_expr` server value variant of `anio` (✨ Generated from Field `Tarifa`.`anio` of type `Int`)
  """
  anio_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `anio` (✨ Generated from Field `Tarifa`.`anio` of type `Int`)
  """
  anio_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd` of type `Float`
  """
  impuestosUsd: Float
  """
  ✨ `_expr` server value variant of `impuestosUsd` (✨ Generated from Field `Tarifa`.`impuestosUsd` of type `Float`)
  """
  impuestosUsd_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `impuestosUsd` (✨ Generated from Field `Tarifa`.`impuestosUsd` of type `Float`)
  """
  impuestosUsd_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tarifa`.`precioUsd` of type `Float!`
  """
  precioUsd: Float
  """
  ✨ `_expr` server value variant of `precioUsd` (✨ Generated from Field `Tarifa`.`precioUsd` of type `Float!`)
  """
  precioUsd_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `precioUsd` (✨ Generated from Field `Tarifa`.`precioUsd` of type `Float!`)
  """
  precioUsd_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tarifa`.`tipo` of type `String!`
  """
  tipo: String
  """
  ✨ `_expr` server value variant of `tipo` (✨ Generated from Field `Tarifa`.`tipo` of type `String!`)
  """
  tipo_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Tarifa'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Tarifa_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Tarifa_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Tarifa_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Tarifa_Filter!]
  """
  ✨ Generated from Field `Tarifa`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Tarifa`.`circuitoId` of type `UUID`
  """
  circuitoId: UUID_Filter
  """
  ✨ Generated from Field `Tarifa`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Filter
  """
  ✨ Generated from Field `Tarifa`.`anio` of type `Int`
  """
  anio: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd` of type `Float`
  """
  impuestosUsd: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`precioUsd` of type `Float!`
  """
  precioUsd: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`tipo` of type `String!`
  """
  tipo: String_Filter
}
"""
✨ Generated first-row input type for table 'Tarifa'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Tarifa_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Tarifa_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Tarifa_Filter
}
"""
✨ Generated having input type for table 'Tarifa'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Tarifa_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Tarifa_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Tarifa_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Tarifa_Having!]
  """
  ✨ Generated from Field `Tarifa`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`anio_count` of type `Int!`
  """
  anio_count: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_count` of type `Int!`
  """
  impuestosUsd_count: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_count` of type `Int!`
  """
  precioUsd_count: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`tipo_count` of type `Int!`
  """
  tipo_count: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`anio_sum` of type `Int`
  """
  anio_sum: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_sum` of type `Float`
  """
  impuestosUsd_sum: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_sum` of type `Float`
  """
  precioUsd_sum: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`anio_avg` of type `Float`
  """
  anio_avg: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_avg` of type `Float`
  """
  impuestosUsd_avg: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_avg` of type `Float`
  """
  precioUsd_avg: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`anio_min` of type `Int`
  """
  anio_min: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_min` of type `Float`
  """
  impuestosUsd_min: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_min` of type `Float`
  """
  precioUsd_min: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`anio_max` of type `Int`
  """
  anio_max: Int_Filter
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_max` of type `Float`
  """
  impuestosUsd_max: Float_Filter
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_max` of type `Float`
  """
  precioUsd_max: Float_Filter
}
"""
✨ Generated key input type for table 'Tarifa'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Tarifa_Key {
  """
  ✨ Generated from Field `Tarifa`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Tarifa`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Tarifa'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Tarifa_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Tarifa_Filter
}
"""
✨ Generated order input type for table 'Tarifa'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Tarifa_Order {
  """
  ✨ Generated from Field `Tarifa`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`circuitoId` of type `UUID`
  """
  circuitoId: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`circuito` of type `Circuito`
  """
  circuito: Circuito_Order
  """
  ✨ Generated from Field `Tarifa`.`anio` of type `Int`
  """
  anio: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd` of type `Float`
  """
  impuestosUsd: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`precioUsd` of type `Float!`
  """
  precioUsd: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`tipo` of type `String!`
  """
  tipo: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`anio_count` of type `Int!`
  """
  anio_count: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`circuitoId_count` of type `Int!`
  """
  circuitoId_count: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_count` of type `Int!`
  """
  impuestosUsd_count: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_count` of type `Int!`
  """
  precioUsd_count: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`tipo_count` of type `Int!`
  """
  tipo_count: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`anio_sum` of type `Int`
  """
  anio_sum: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_sum` of type `Float`
  """
  impuestosUsd_sum: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_sum` of type `Float`
  """
  precioUsd_sum: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`anio_avg` of type `Float`
  """
  anio_avg: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_avg` of type `Float`
  """
  impuestosUsd_avg: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_avg` of type `Float`
  """
  precioUsd_avg: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`anio_min` of type `Int`
  """
  anio_min: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_min` of type `Float`
  """
  impuestosUsd_min: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_min` of type `Float`
  """
  precioUsd_min: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`anio_max` of type `Int`
  """
  anio_max: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`impuestosUsd_max` of type `Float`
  """
  impuestosUsd_max: OrderDirection
  """
  ✨ Generated from Field `Tarifa`.`precioUsd_max` of type `Float`
  """
  precioUsd_max: OrderDirection
}
"""
✨ Generated data input type for table 'User'. It includes all necessary fields for creating or upserting rows into table.
"""
input User_Data {
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String
  """
  ✨ `_expr` server value variant of `displayName` (✨ Generated from Field `User`.`displayName` of type `String!`)
  """
  displayName_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`email` of type `String`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `User`.`email` of type `String`)
  """
  email_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String
  """
  ✨ `_expr` server value variant of `photoUrl` (✨ Generated from Field `User`.`photoUrl` of type `String`)
  """
  photoUrl_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'User'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [User_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: User_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [User_Filter!]
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: String_Filter
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String_Filter
  """
  ✨ Generated from Field `User`.`email` of type `String`
  """
  email: String_Filter
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String_Filter
  """
  ✨ Generated from Field `User`.`reservacions_on_usuario` of type `[Reservacion!]!`
  """
  reservacions_on_usuario: Reservacion_ListFilter
}
"""
✨ Generated first-row input type for table 'User'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input User_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [User_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: User_Filter
}
"""
✨ Generated having input type for table 'User'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [User_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: User_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [User_Having!]
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: Int_Filter
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'User'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input User_Key {
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'User'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input User_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: User_Filter
}
"""
✨ Generated order input type for table 'User'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input User_Order {
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: OrderDirection
  """
  ✨ Generated from Field `User`.`email` of type `String`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: OrderDirection
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: OrderDirection
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
